### ISSUE TITLE
[Task] Overworld (RPG κομμάτι του παχνιδιού)

### ISSUE THREAD

**Issue by vkyrillidis** [eap-pegasus-team/aranthia#25]
Δημιουργία game scene το οποίο θα εμφανίζει το overworld κομμάτι του παιχνιδιού το οποίο θα είναι grid based 2D.  

Θα περιέχει τα εξής:
- [x] Τον κεντρικό χάρτη στον οποίο ο παίκτης μπορεί να δει την "ακαδημία" της Aranthia
- [x] Μπορεί να μετακινηθεί δεξιά, αριστερά, πάνω και κάτω (top-down view)
- [x] Μπορεί να αλληλεπιδράσει με τις διάφορες σχολές μαγείας (πηγαίνοντας στην πόρτα τους όπου θα ερωτηθεί αν θέλει να παρακολουθήσει το μάθημα)
- [x] Δημιουργία sparring arena όπου ο παίκτης μπορεί να πολεμίσει ενάντια σε κάποιον/κάτι
- [x] Ανανέωση των γραφικών του παιχνιδιού (με αυτά που ετοίμασε ο Νίκος)
- [x] Trigger από το overworld στο visual novel κομμάτι του παιχνιδιού κάθε φορά που μπαίνουμε σε "πόρτα"

**Comment by andrew-pliakis** [comment]
Δημιουργία event για έναρξη μάχης/αλληλεπίδραση με npc

**Comment by vkyrillidis** [comment]
- [ ] Stretch: Μπορεί με το πλήκτρο ESC να δείξει το pause menu
- [ ] Stretch: Μπορεί με το πλήκτρο M να εμφανίσει το χάρτη της σχολής
