### ISSUE TITLE
Προετοιμασία tutorial

### ISSUE THREAD

**Issue by vkyrillidis** [eap-pegasus-team/aranthia#9]
Περιγραφή του αρχικού tutorial του παιχνιδιού

Διάλογοι, σκηνοθεσία

**Comment by GeorgePournaras** [comment]
[Tutorial.DOCX](https://github.com/eap-pegasus-team/aranthia/files/11501822/Tutorial.DOCX)

Ελπίζω να δουλέψει έτσι.
